server:
  servlet:
    context-path: /bookshop
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.129/bookshop07?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.124.129
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 10
  rabbitmq:
    host: 192.168.124.129
    port: 5672
    username: yan
    password: 123456

  elasticsearch:
    rest:
      uris: 192.168.124.129:9200
      connection-timeout: 100000
      read-timeout: 50000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
  global-config:
    banner: false

shiro:
  unauthorizedUrl: /view/403.html
  loginUrl: /login.html
  successUrl: /view/index.html

beetl:
  enabled: false
beetl-beetlsql:
  dev: false

logging:
  pattern:
    console: level - %p - %m%n
  level:
    root: warn


